Repository pubnub/c-core, pull requests merged in 2024-08, with the labels that each got.

#191 Fix history query parameter values
  .pubnub.yml
  CHANGELOG.md
  core/pbcc_fetch_history.c
  core/pubnub_version_internal.h
  core/samples/pubnub_fetch_history_sample.c
Labels: status: done, priority: medium, type: fix

#193 fix custom `bool` type for CMake builds
  .pubnub.yml
  CHANGELOG.md
  CMakeLists.txt
  core/pubnub_version_internal.h
Labels: priority: high, type: fix

#192 Add missing `ttl` parameter
  .pubnub.yml
  CHANGELOG.md
  core/pubnub_ccore_pubsub.c
  core/pubnub_ccore_pubsub.h
  core/pubnub_coreapi_ex.c
  core/pubnub_coreapi_ex.h
  core/pubnub_objects_api.c
  core/pubnub_pubsubapi.c
  core/pubnub_version_internal.h
  core/samples/pubnub_publish_via_post_sample.c
Labels: status: done, priority: high, type: fix

#194 Add delete messages API
  .pubnub.yml
  CHANGELOG.md
  core/pbcc_advanced_history.c
  core/pbcc_advanced_history.h
  core/pubnub_advanced_history.c
  core/pubnub_advanced_history.h
  core/pubnub_api_types.h
  core/pubnub_netcore.c
  core/pubnub_version_internal.h
  core/samples/pubnub_advanced_history_sample.c
  qt/pubnub_qt.cpp
Labels: status: done, priority: high, type: feature
