Repository pubnub/c-core, pull requests merged in 2025-01, with the labels that each got.

#202 Remove length limit from user id
  .pubnub.yml
  CHANGELOG.md
  CMakeLists.txt
  core/Makefile
  core/pubnub_ccore_pubsub.c
  core/pubnub_core_unit_test.c
  core/pubnub_version_internal.h
  lib/Makefile
Labels: status: done, priority: high, type: fix

#201 Add logging callback
  .pubnub.yml
  CHANGELOG.md
  CMakeLists.txt
  core/Makefile
  core/pubnub_internal_common.h
  core/pubnub_log.c
  core/pubnub_log.h
  core/pubnub_version_internal.h
  core/test/pubnub_config.h
  make/common/preprocessing.mk
  make/common/preprocessing_defaults.mk
  make/common/source_files.mk
  make/posix_preprocessing.mk
  make/windows_preprocessing.mk
  openssl/pubnub_config.h
  posix/pubnub_config.h
  windows/pubnub_config.h
Labels: status: done

#203 Add `SDK_VERSION_SUFFIX` for partner id
  .github/workflows/run-tests.yml
  CMakeLists.txt
Labels: status: done, priority: medium, type: build
